---
- hosts: localhost
  vars:
    type: m4.4xlarge
    keyname: alex
    sg: sg-785ac703
    name: "CeleryGrid-{{ repos.sixty }}-db{{ env.REDIS_DB }}"
    count: 7
    repos:
      sixty: develop
    env:
      REDIS_DB: 3
  roles:
  - { role: deploy_ec2, nodename: "{{ name }}-master", class: "master", number: 1 }
  - { role: deploy_ec2_worker, nodename: "{{ name }}", class: "worker", number: "{{ count }}" }

- hosts: worker
  remote_user: ubuntu
  vars:
    tag: latest
    repos:
      sixty: develop
    env:
      REDIS_DB: 3
      IS_CELERY_WORKER: 1
      C_FORCE_ROOT: 1
      SIXTY_CONFIG_FILE: "~/workspace/sixty/config.yaml"
  roles:
    - git 
    - docker
    - docker_celery
    - celery_worker

- hosts: master
  remote_user: ubuntu
  vars:
    tag: latest
    repos:
      sixty: develop
    env:
      REDIS_DB: 3
      IS_CELERY_WORKER: 1
      SIXTY_CONFIG_FILE: "~/workspace/sixty/config.yaml"
    etl_start: "workspace/sixty/sixty/etl/start_etl.py -d today"
  roles:
    - git
    - docker
    - docker_celery
    - celery_flower
    - celery_etl

- hosts: localhost
  tasks:
  - name: delete machines
    ec2:
      region: "{{ item.instances.0.region }}"
      state: absent
      instance_ids: "{{ item.instance_ids }}"
    with_items:
    - "{{ ec2 }}"
    - "{{ ec2worker }}"
