---
- hosts: localhost
  vars:
    type: t2.large
    keyname: alex
    sg: sg-785ac703
    name: celery
    class: worker
  roles:
  - { role: deploy_ec2, nodename: "{{ name }}",  number: "{{ count }}" }

- hosts: worker
  remote_user: ubuntu
  vars:
    tag: latest
    repos:
      sixty: develop
    env:
      REDIS_DB: 3
      IS_CELERY_WORKER: 1
      C_FORCE_ROOT: 1
      SIXTY_CONFIG_FILE: ~/workspace/sixty/config.yaml
  roles:
    - put-admin-key
    - git 
    - docker
    - docker_celery
    - celery_worker
