---

- hosts: localhost
  vars:
    region: us-east-1
    image: ami-fce3c696
    type: t2.large
    keyname: infrastructure
    sg: sg-4a28e12d
    vpc_subnet_id: subnet-64b0a04c
    name: celery
    class: dev
    count: 1
    email: admin@sixtycapital.com
    

  tasks:
  - name: launch temporary instance
    ec2:
      assign_public_ip: yes
      region: "{{ region }}"
      key_name: "{{ keyname }}"
      group: "{{ sg }}"
      instance_type: "{{ type }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      image: "{{ image }}"
      wait: yes
      wait_timeout: 500
      count: "{{ count }}"
      instance_tags:
          Name: "{{ name }}"
          class: "{{ class }}"
      wait: yes
      wait_timeout: 300
    register: ec2 

  - name: waiting for ssh to start
    wait_for: port=22 host={{ item.public_dns_name }} timeout=300
              search_regex=OpenSSH
    with_items: ec2.instances

  - name: add host to group
    add_host: name={{ item.public_ip }} groups=dev
    with_items: ec2.instances    


- hosts: dev
  remote_user: ubuntu
  vars:
    redis_db: 1
    type: "{{ hostvars['localhost']['ec2']['instances'][0]['instance_type'] }}"
    repos:
    - { repo: sixty, branch: develop }
  roles:
     - atlas
     - development
     - celery

