---

- hosts: localhost
  vars:
    region: us-east-1
    image: ami-fce3c696
    type: t2.large
    keyname: alex
    sg: sg-4a28e12d
    vpc_subnet_id: subnet-64b0a04c
    name: celery
    class: dev
    count: 1

  tasks:
  - name: launch temporary instance
    ec2:
      assign_public_ip: yes
      region: "{{ region }}"
      key_name: "{{ keyname }}"
      group: "{{ sg }}"
      instance_type: "{{ type }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      instance_profile_name: ecsInstanceRole
      image: "{{ image }}"
      wait: yes
      wait_timeout: 500
      count: "{{ count }}"
      instance_tags:
          Name: "{{ name }}"
          class: "{{ class }}"
      wait: yes
      wait_timeout: 300
    register: ec2 

  - name: waiting for ssh to start
    wait_for: port=22 host={{ item.public_dns_name }} timeout=300
              search_regex=OpenSSH
    with_items: ec2.instances

  - name: add host to group
    add_host: name={{ item.public_ip }} groups=dev
    with_items: ec2.instances    


- hosts: dev
  remote_user: ubuntu
  vars:
    tag: latest
    repos:
      sixty: develop
    env:
      REDIS_DB: 1 
      IS_CELERY_WORKER: 1
      SIXTY_CONFIG_FILE: ~/workspace/sixty/config.yaml
      PYTHONPATH: /home/ubuntu/workspace/sixty
  roles:
    - git 
    - celery_docker
    - celery_worker
