---

- hosts: localhost
  vars:
    region: us-east-1
    image: ami-fce3c696
    root_size: 30
    type: t2.large
    keyname: alex
    sg: sg-4a28e12d
    vpc_subnet_id: subnet-64b0a04c
    name: development
    class: dev
    count: 1
  roles:
  - deploy_ec2

- hosts: dev
  remote_user: ubuntu
  vars:
    tag: latest
    repos:
      sixty: develop
      infrastructure: master
  roles:
    - put-admin-key
    - development_docker
    - git
