---
- hosts: localhost
  vars:
    type: t2.large
    keyname: alex
    sg: sg-4a28e12d
    name: builder
    class: dev
  roles:
  - { role: deploy_ec2, nodename: "{{ name }}",  number: "{{ count }}" }
  tags: always

- hosts: dev
  remote_user: ubuntu
  vars:
    tag: test
    repos:
      infrastructure: master
  roles:
    - { role: docker, tags: always }
    - { role: git, tags: always }
    - build_container

- hosts: localhost
  tasks:
  - name: delete temporary instance
    ec2:
      region: "{{ ec2.instances.0.region }}"
      state: absent
      instance_ids: "{{ ec2.instance_ids }}"
    tags: always
