---

- hosts: localhost
  vars:
    region: us-east-1
    image: ami-fce3c696
    type: m4.4xlarge
    keyname: alex
    sg: sg-4a28e12d
    vpc_subnet_id: subnet-64b0a04c
    name: celery-grid
    class: dev
    count: 7

  tasks:
  - name: launch worker instances
    ec2:
      assign_public_ip: yes
      region: "{{ region }}"
      key_name: "{{ keyname }}"
      group: "{{ sg }}"
      instance_type: "{{ type }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      image: "{{ image }}"
      wait: yes
      wait_timeout: 500
      count: "{{ count }}"
      instance_tags:
          Name: "{{ name }}"
          class: "{{ class }}"
      wait: yes
      wait_timeout: 300
    register: ec2 

  - name: waiting for ssh to start
    wait_for: port=22 host={{ item.public_dns_name }} timeout=300
              search_regex=OpenSSH
    with_items: ec2.instances

  - name: add host to group
    add_host: name={{ item.public_ip }} groups=workers
    with_items: ec2.instances

  - name: launch master instance
    ec2:
      assign_public_ip: yes
      region: "{{ region }}"
      key_name: "{{ keyname }}"
      group: "{{ sg }}"
      instance_type: "{{ type }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      image: "{{ image }}"
      wait: yes
      wait_timeout: 500
      count: 1
      instance_tags:
          Name: "{{ name }}-master"
          class: "{{ class }}"
      wait: yes
      wait_timeout: 300
    register: ec2


  - name: waiting for ssh to start
    wait_for: port=22 host={{ item.public_dns_name }} timeout=300
              search_regex=OpenSSH
    with_items: ec2.instances

  - name: add host to group
    add_host: name={{ item.public_ip }} groups=master
    with_items: ec2.instances

- hosts: workers
  remote_user: ubuntu
  vars:
    tag: latest
    email: admin@sixtycapital.com
    repos:
    - { repo: sixty, branch: fake_celery }
    env:
    - { name: REDIS_DB, value: 1 }
    - { name: IS_CELERY_WORKER, value: 1 }
    - { name: SIXTY_CONFIG_FILE, value: ~/workspace/sixty/config.yaml }
    - { name: PYTHONPATH, value: /home/ubuntu/workspace/sixty }
  roles:
    - git 
    - celery_worker

- hosts: master
  remote_user: ubuntu
  vars:
    tag: latest
    email: admin@sixtycapital.com
    repos:
    - { repo: sixty, branch: fake_celery }
    env:
    - { name: REDIS_DB, value: 1 }
    - { name: IS_CELERY_WORKER, value: 1 }
    - { name: SIXTY_CONFIG_FILE, value: ~/workspace/sixty/config.yaml }
    - { name: PYTHONPATH, value: /home/ubuntu/workspace/sixty }
    etl_args: ""
  roles:
    - git
    - celery_flower
    - celery_etl
