---
- hosts: localhost
  vars:
    region: us-east-1
    image: ami-fce3c696
    root_size: 30
    type: m4.4xlarge
    keyname: alex
    sg: sg-785ac703
    vpc_subnet_id: subnet-64b0a04c
    name: "CeleryGrid-{{ repos.sixty }}-db{{ env.REDIS_DB }}"
    count: 7
    repos:
      sixty: develop
    env:
      REDIS_DB: 3
  roles:
  - { role: deploy_ec2, name: "{{ name }}-master", class: "master", count: 1 }
  - { role: deploy_ec2, name: "{{ name }}", class: "worker"}

- hosts: worker
  remote_user: ubuntu
  vars:
    tag: test
    repos:
      sixty: develop
    env:
      REDIS_DB: 3
      IS_CELERY_WORKER: 1
      C_FORCE_ROOT: 1
      SIXTY_CONFIG_FILE: "~/workspace/sixty/config.yaml"
  roles:
    - git 
    - celery_worker

- hosts: master
  remote_user: ubuntu
  vars:
    tag: test
    repos:
      sixty: develop
    env:
      REDIS_DB: 3
      IS_CELERY_WORKER: 1
      SIXTY_CONFIG_FILE: "~/workspace/sixty/config.yaml"
    etl_start: "workspace/sixty/sixty/etl/start_etl.py"
  roles:
    - git
    - celery_flower
    - celery_etl

- hosts: localhost
  tasks:
  - name: delete machines
    ec2:
      region: "{{ item.instances.0.region }}"
      state: absent
      instance_ids: "{{ item.instance_ids }}"
    with_items:
    - "{{ ec2 }}"
