---

- hosts: localhost
  vars:
    region: us-east-1
    image: ami-fce3c696
    root_size: 30
    type: t2.large
    keyname: alex
    sg: sg-8258c5f9
    vpc_subnet_id: subnet-64b0a04c
    name: notebook
    class: dev
    count: 1
  roles:
  - deploy_ec2

- hosts: dev
  remote_user: ubuntu
  vars:
    tag: test
    repos:
      sixty: develop
      infrastructure: master
  roles:
    - put-admin-key
    - git
    - jupyter_docker
