---

- hosts: localhost
  vars:
    region: us-east-1
    image: ami-fce3c696
    root_size: 30
    type: t2.large
    keyname: alex
    sg: sg-785ac703
    vpc_subnet_id: subnet-64b0a04c
    name: celery
    class: worker
    count: 1
  roles:
  - deploy_ec2

- hosts: worker
  remote_user: ubuntu
  vars:
    tag: test
    repos:
      sixty: develop
    env:
      REDIS_DB: 3
      IS_CELERY_WORKER: 1
      C_FORCE_ROOT: 1
      SIXTY_CONFIG_FILE: ~/workspace/sixty/config.yaml
  roles:
    - put-admin-key
    - git 
    - celery_worker
